import {
    LuUtensils,
    LuCar,
    LuBadgeDollarSign,
    LuFilm,
    LuShoppingBag,
    LuHeartPulse,
} from "react-icons/lu";

export const categories = [
    {
        id: 1,
        title: "Food & Dining",
        icon: LuUtensils,
        color: "#F97316",
        transactions: 24,
        spent: 4200,
        limit: 5000,
        subcategories: [
            "Groceries",
            "Restaurants",
            "Coffee",
            "Fast Food",
            "Snacks",
        ],
    },
    {
        id: 2,
        title: "Transportation",
        icon: LuCar,
        color: "#2563EB",
        transactions: 10,
        spent: 6000,
        limit: 8000,
        subcategories: [
            "Fuel",
            "Parking",
            "Taxi",
            "Bus",
        ],
    },
    {
        id: 3,
        title: "Bills & Utilities",
        icon: LuBadgeDollarSign,
        color: "#EAB308",
        transactions: 13,
        spent: 2000,
        limit: 1000,
        subcategories: [
            "Electricity",
            "Water",
            "Internet",
            "Mobile Load",
            "Rent",
        ],
    },
    {
        id: 4,
        title: "Entertainment",
        icon: LuFilm,
        color: "#9333EA",
        transactions: 8,
        spent: 1800,
        limit: 2500,
        subcategories: [
            "Movies",
            "Games",
            "Streaming",
            "Concerts",
            "Books",
        ],
    },
    {
        id: 5,
        title: "Shopping",
        icon: LuShoppingBag,
        color: "#EC4899",
        transactions: 17,
        spent: 3600,
        limit: 4000,
        subcategories: [
            "Clothing",
            "Shoes",
            "Accessories",
            "Electronics",
            "Home",
        ],
    },
    {
        id: 6,
        title: "Health",
        icon: LuHeartPulse,
        color: "#EF4444",
        transactions: 6,
        spent: 900,
        limit: 1500,
        subcategories: [
            "Medicine",
            "Doctor",
            "Dental",
            "Gym",
            "Vitamins",
        ],
    },
];