const transactions = [
    {
        id: 1,
        date: "Jul 31, 2026",
        description: "Monthly Salary",
        category: "Income",
        subcategory: "Salary",
        type: "Income",
        amount: 50000,
    },
    {
        id: 2,
        date: "Jul 30, 2026",
        description: "Grocery Shopping",
        category: "Food",
        subcategory: "Groceries",
        type: "Expense",
        amount: -1250,
    },
    {
        id: 3,
        date: "Jul 30, 2026",
        description: "Coffee",
        category: "Food",
        subcategory: "Coffee",
        type: "Expense",
        amount: -180,
    },
    {
        id: 4,
        date: "Jul 29, 2026",
        description: "Electric Bill",
        category: "Bills",
        subcategory: "Electricity",
        type: "Expense",
        amount: -3200,
    },
    {
        id: 5,
        date: "Jul 29, 2026",
        description: "Water Bill",
        category: "Bills",
        subcategory: "Water",
        type: "Expense",
        amount: -950,
    },
    {
        id: 6,
        date: "Jul 28, 2026",
        description: "Internet Subscription",
        category: "Bills",
        subcategory: "Internet",
        type: "Expense",
        amount: -1699,
    },
    {
        id: 7,
        date: "Jul 28, 2026",
        description: "Gas",
        category: "Transportation",
        subcategory: "Fuel",
        type: "Expense",
        amount: -1800,
    },
    {
        id: 8,
        date: "Jul 27, 2026",
        description: "Grab Ride",
        category: "Transportation",
        subcategory: "Ride Sharing",
        type: "Expense",
        amount: -320,
    },
    {
        id: 9,
        date: "Jul 27, 2026",
        description: "Netflix",
        category: "Entertainment",
        subcategory: "Streaming",
        type: "Expense",
        amount: -549,
    },
    {
        id: 10,
        date: "Jul 26, 2026",
        description: "Cinema Tickets",
        category: "Entertainment",
        subcategory: "Movies",
        type: "Expense",
        amount: -650,
    },
    {
        id: 11,
        date: "Jul 25, 2026",
        description: "Freelance Project",
        category: "Income",
        subcategory: "Freelancing",
        type: "Income",
        amount: 12000,
    },
    {
        id: 12,
        date: "Jul 25, 2026",
        description: "Restaurant Dinner",
        category: "Food",
        subcategory: "Dining Out",
        type: "Expense",
        amount: -1450,
    },
    {
        id: 13,
        date: "Jul 24, 2026",
        description: "Mobile Load",
        category: "Utilities",
        subcategory: "Mobile",
        type: "Expense",
        amount: -299,
    },
    {
        id: 14,
        date: "Jul 24, 2026",
        description: "Pharmacy",
        category: "Healthcare",
        subcategory: "Medicine",
        type: "Expense",
        amount: -780,
    },
    {
        id: 15,
        date: "Jul 23, 2026",
        description: "Clothing Purchase",
        category: "Shopping",
        subcategory: "Clothing",
        type: "Expense",
        amount: -2499,
    },
    {
        id: 16,
        date: "Jul 22, 2026",
        description: "Dividend Payout",
        category: "Income",
        subcategory: "Investments",
        type: "Expense",
        amount: 3500,
    },
    {
        id: 17,
        date: "Jul 21, 2026",
        description: "Bookstore",
        category: "Education",
        subcategory: "Books",
        type: "Expense",
        amount: -890,
    },
    {
        id: 18,
        date: "Jul 20, 2026",
        description: "Gym Membership",
        category: "Health & Fitness",
        subcategory: "Gym",
        type: "Expense",
        amount: -1200,
    },
    {
        id: 19,
        date: "Jul 19, 2026",
        description: "Birthday Gift",
        category: "Others",
        subcategory: "Gifts",
        type: "Expense",
        amount: -1500,
    },
    {
        id: 20,
        date: "Jul 18, 2026",
        description: "Savings Deposit",
        category: "Savings",
        subcategory: "Emergency Fund",
        type: "Expense",
        amount: -5000,
    },
];

export default transactions;